CREATE TABLE IF NOT EXISTS USERS (
  USER_ID           INT PRIMARY KEY AUTO_INCREMENT,
  Login             VARCHAR(50)  NOT NULL,
  Password          VARCHAR(100) NOT NULL,
  Email             VARCHAR(50)  NOT NULL,
  First_name        VARCHAR(50),
  Last_name         VARCHAR(50),
  BIRTH_DAY         DATE,
  REGISTRATION_DATE DATE         NOT NULL);


CREATE TABLE IF NOT EXISTS TASKS (
  TASK_ID     INT PRIMARY KEY AUTO_INCREMENT,
  PROJECT_ID  INT,
  USER_ID     INT,
  "Name"      VARCHAR(50)  NOT NULL,
  Description VARCHAR(300) NOT NULL,
  PRIORITY    SMALLINT,
  STATUS      BIT,
  ATTACHMENT  BIT,
  START_DATE  DATE         NOT NULL,
  END_DATE    DATE         NOT NULL,
  TASK_TYPE   VARCHAR(1));


ALTER TABLE TASKS ADD FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);


CREATE TABLE IF NOT EXISTS ATTACHMENTS (
  ATTACHMENT_ID   INT PRIMARY KEY AUTO_INCREMENT,
  ATTACHMENT_TYPE VARCHAR(5) NOT NULL,
  FILE_LINK       VARCHAR(1000),
  USER_ID         INT        NOT NULL,
  DESCRIPTION     VARCHAR(1000));


ALTER TABLE ATTACHMENTS ADD FOREIGN KEY (TASKS) REFERENCES TASKS (TASK_ID);

CREATE TABLE IF NOT EXISTS HISTORY (
  ID          INT,
  USER_ID     INT,
  TABLE_NAME  VARCHAR(50),
  COLUMN_NAME VARCHAR(50),
  OLD_VALUE   INT,
  NEW_VALUE   INT);


ALTER TABLE HISTORY ADD FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);