CREATE TABLE IF NOT EXISTS TASKS (
  TASK_ID     INT PRIMARY KEY AUTO_INCREMENT,
  PROJECT_ID  INT,
  USER_ID     INT,
  NAME      VARCHAR(250)  NOT NULL,
  DESCRIPTION VARCHAR(300),
  PRIORITY    SMALLINT,
  STATUS      INT,
  ATTACHMENT  INT, //REFERENCE TO ATTACHMENT_ID
  START_DATE  DATE,
  END_DATE    DATE,
  TASK_TYPE   VARCHAR(1));


ALTER TABLE TASKS ADD FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
