CREATE TABLE IF NOT EXISTS HISTORY (
  ID          INT,
  USER_ID     INT,
  TABLE_NAME  VARCHAR(50),
  COLUMN_NAME VARCHAR(50),
  OLD_VALUE   INT,
  NEW_VALUE   INT);


ALTER TABLE HISTORY ADD FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);